version: '3.4'

services:
  identity:
    container_name: identity
    image: ${DOCKER_REGISTRY-}identity
    ports:
      - "3001:80"
    build:
      context: .
      dockerfile: Identity/Dockerfile
    environment:
      CONNECTION_STRING: "Server=tcp:madcn.database.windows.net,1433;Initial Catalog=Identity;Persist Security Info=False;User ID=dimlucas;Password=abc123@!#;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"

  api:
    container_name: api
    image: ${DOCKER_REGISTRY-}api
    ports:
      - "3002:80"
    build:
      context: .
      dockerfile: API/Dockerfile
    environment:
      CONNECTION_STRING: "Server=tcp:madcn.database.windows.net,1433;Initial Catalog=MainDb;Persist Security Info=False;User ID=dimlucas;Password=abc123!@#;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
